const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");

const appConfig = JSON.parse(read("miniprogram/app.json"));
const appJs = read("miniprogram/app.js");
const partnersJs = read("miniprogram/pages/partners/partners.js");
const partnersWxml = read("miniprogram/pages/partners/partners.wxml");
const chatJs = read("miniprogram/pages/social-chat/social-chat.js");
const chatWxml = read("miniprogram/pages/social-chat/social-chat.wxml");
const contactJs = read("miniprogram/pages/social-contact/social-contact.js");
const contactWxml = read("miniprogram/pages/social-contact/social-contact.wxml");
const profileService = read("miniprogram/services/social-profile.js");
const socialService = read("miniprogram/services/social.js");
const socialChatCache = read("miniprogram/services/social-chat-cache.js");
const socialCloud = [
  read("cloudfunctions/social/index.js"),
  read("cloudfunctions/social/social-utils.js"),
  read("cloudfunctions/social/social-inbox.js"),
  read("cloudfunctions/social/social-store.js"),
  read("cloudfunctions/social/social-action-router.js")
].join("\n");

assert.ok(appConfig.pages.includes("pages/partners/partners"));
assert.ok(appConfig.pages.includes("pages/social-chat/social-chat"));
assert.ok(appConfig.pages.includes("pages/social-contact/social-contact"));
assert.ok(!appConfig.pages.includes("pages/social-inbox/social-inbox"));
assert.ok(appConfig.tabBar.list.some(item => item.pagePath === "pages/partners/partners" && item.text === "伙伴"));
assert.ok(appJs.includes("showTabBarRedDot"));
assert.ok(appJs.includes("hideTabBarRedDot"));
assert.ok(!appJs.includes("setTabBarBadge"));
assert.ok(partnersWxml.includes("朋友"));
assert.ok(partnersWxml.includes("招呼"));
assert.ok(partnersWxml.includes("conversation-list"));
assert.ok(partnersWxml.includes("notice-dot"));
assert.ok(partnersWxml.indexOf("朋友") < partnersWxml.indexOf("招呼"));
assert.ok(partnersWxml.includes('data-section="friends"'));
assert.ok(partnersWxml.includes('data-section="greetings"'));
assert.ok(partnersWxml.includes('catchtap="respondGreeting"'));
assert.ok(partnersWxml.includes('bindtap="loadMore"'));
assert.ok(partnersJs.includes("friendCursor"));
assert.ok(partnersJs.includes("greetingCursor"));
assert.ok(partnersJs.includes("scheduleRefresh"));
assert.ok(!partnersJs.includes("setInterval"));
assert.ok(!partnersWxml.includes("微信消息提醒"));
assert.ok(!partnersWxml.includes('bindtap="enableNotifications"'));
assert.ok(!partnersWxml.includes('data-view="messages"'));
assert.ok(!partnersWxml.includes('data-view="people"'));
assert.ok(partnersJs.includes("hasNotice"));
assert.ok(partnersJs.includes('setForegroundView("partners")'));
assert.ok(partnersJs.includes("你们已经互相认识啦"));
assert.ok(partnersJs.includes("toggleSection"));
assert.ok(chatWxml.includes("发一句问候"));
assert.ok(chatJs.includes("你好，很高兴认识你"));
assert.ok(chatJs.includes("有空一起散步吗"));
assert.ok(chatWxml.includes("emojis"));
assert.ok(chatWxml.includes("由你确认后再发送"));
assert.ok(chatWxml.includes("contact-access-summary"));
assert.ok(chatWxml.includes('bindtap="openContactExchange"'));
assert.ok(!chatWxml.includes("contact-panel"));
assert.ok(!chatWxml.includes('bindtap="toggleContactOption"'));
assert.ok(!chatWxml.includes('bindinput="onContactInput"'));
assert.ok(contactWxml.includes("你的资料预设只保存在本机"));
assert.ok(contactWxml.includes("分享所选资料"));
assert.ok(contactWxml.includes("管理本机资料"));
assert.ok(contactWxml.includes('bindtap="toggleOption"'));
assert.ok(contactWxml.includes("撤回当前分享"));
assert.ok(contactJs.includes("profileService.getProfile()"));
assert.ok(contactJs.includes("socialChatCache.patchConversation"));
assert.ok(chatWxml.includes('bindlongpress="reportMessage"'));
assert.ok(chatWxml.includes("单人测试模式"));
assert.ok(chatWxml.includes('<input class="message-input"'));
assert.ok(chatWxml.includes('bindconfirm="sendMessage"'));
assert.ok(chatWxml.includes("加载更早消息"));
assert.ok(chatWxml.includes("messagePolicy.tip"));
assert.ok(chatJs.includes("已发送 3 条，请等待对方回复"));
assert.ok(!chatWxml.includes('<textarea class="message-input"'));
assert.ok(chatJs.includes("beforeCreatedAt"));
assert.ok(chatJs.includes("afterCreatedAt"));
assert.ok(chatJs.includes("mergeMessages"));
assert.ok(chatJs.includes("runSoloTestAction"));
assert.ok(chatJs.includes("scheduleRefresh"));
assert.ok(chatJs.includes("conversationSignature"));
assert.ok(chatJs.includes("restoreCachedConversation"));
assert.ok(chatJs.includes("persistConversationCache"));
assert.ok(chatJs.includes("result && result.message"));
assert.ok(chatJs.includes("socialChatCache.removeConversation"));
assert.ok(socialChatCache.includes("MAX_MESSAGES_PER_CONVERSATION"));
assert.ok(socialChatCache.includes("CACHE_FRESH_MS"));
assert.ok(!chatJs.includes("setInterval"));
assert.ok(chatJs.includes("confirmEndRelationship"));
assert.ok(chatJs.includes("confirmBlockUser"));
assert.ok(chatJs.includes("clearConversationForMe"));
assert.ok(socialService.includes('action: "getConversation"'));
assert.ok(socialService.includes("source.afterCreatedAt"));
assert.ok(socialService.includes('action: "sendSocialMessage"'));
assert.ok(socialService.includes('action: "requestContactExchange"'));
assert.ok(socialService.includes('action: "cancelContactExchange"'));
assert.ok(socialService.includes('action: "getContactExchange"'));
assert.ok(socialService.includes("contactItems"));
assert.ok(socialService.includes('action: "stageContactQr"'));
assert.ok(socialService.includes('action: "cancelStagedContactShare"'));
assert.ok(socialService.includes("readPendingContactShare"));
assert.ok(socialService.includes("requestId: pending.requestId"));
assert.ok(!profileService.includes("contactOptions: profile.contactOptions.map"));
assert.ok(socialService.includes('action: "reportMessage"'));
assert.ok(socialService.includes('action: "prepareSoloTestPartner"'));
assert.ok(socialService.includes('action: "soloTestPeerAction"'));
assert.ok(socialCloud.includes("MESSAGE_COLLECTION"));
assert.ok(socialCloud.includes("CONTACT_REQUEST_COLLECTION"));
assert.ok(socialCloud.includes("BLOCK_COLLECTION"));
assert.ok(socialCloud.includes("REPORT_COLLECTION"));
assert.ok(socialCloud.includes("normalizeRequestId"));
assert.ok(socialCloud.includes("containsRestrictedLink"));
assert.ok(socialCloud.includes("MESSAGE_LIMIT_PER_MINUTE"));
assert.ok(socialCloud.includes("GREETING_PRE_REPLY_MESSAGE_LIMIT"));
assert.ok(socialCloud.includes('orderBy("inboxSortKey", "desc")'));
assert.ok(socialCloud.includes("CONTACT_STAGE_TTL_MS"));
assert.ok(socialCloud.includes("lastShareFingerprint"));
assert.ok(socialCloud.includes("对方回复前最多发送 3 条消息"));
assert.ok(socialCloud.includes('.orderBy("createdAt", direction === "after" ? "asc" : "desc")'));
assert.ok(!socialCloud.includes("subscribeMessage.send"));
assert.ok(!socialCloud.includes("NOTIFICATION_SUBSCRIPTION_COLLECTION"));
assert.ok(socialCloud.includes("soloTestPeerOwnerKey"));

const socialChatSources = `${chatJs}\n${read("miniprogram/pages/social-chat/social-chat-helpers.js")}\n${chatWxml}`;
["RecorderManager", "startRecord", "transcribe", "语音消息", "语音通话", "video"].forEach(forbidden => {
  assert.ok(!socialChatSources.includes(forbidden), `伙伴聊天不应包含 ${forbidden}`);
});

console.log("social text chat tests passed");
